{edoc_opts, [{sort_functions, false}]},
case os:cmd("git branch") of 
    % "* master\n" -> 
    _ -> 
[
{sub_dirs,[ ]},

{erl_opts, [debug_info,fail_on_warning,{d,debug},{d,timestamp},{d,newdebug},{parse_transform,lager_transform}]},
%{erl_opts, [debug_info,fail_on_warning,{parse_transform,lager_transform}]},

{require_otp_vsn, ""},

        {deps,
            [
            {lager,".*",{git,"https://github.com/erlang-lager/lager.git","master"}},
            {newdebug,".*",{git,"https://github.com/stobix/newdebug","master"}},
            {numberer,".*",{git,"https://github.com/stobix/numberer","master"}},
            {tree_app,".*",{git,"https://github.com/stobix/tree_app","master"}},
            {reporter,".*",{git,"https://github.com/stobix/reporter","master"}},
            {options,".*",{git,"https://github.com/stobix/options","master"}},
            {vol_tools,".*",{git,"https://github.com/stobix/vol_tools","master"}},
            {erlando,".*",{git,"https://github.com/stobix/erlando","master"}},
            {pid_numberer,".*",{git,"https://github.com/stobix/pid_numberer","master"}},
            {fuserl,".*",{git,"https://github.com/stobix/fuserl","master"}}
        ] }

];
    _ -> 
[
{sub_dirs,[ ]},

{deps_dir,exp_deps},

{erl_opts, [debug_info,fail_on_warning,{d,debug},{d,timestamp},{d,newdebug},{parse_transform,lager_transform}]},

{require_otp_vsn, ""},

        {deps,
            [
            {newdebug,".*",{hg,"https://github.com/stobix/newdebug","tip"}},
            {reporter,".*",{hg,"https://github.com/stobix/reporter","tip"}},
            {options,".*",{hg,"https://github.com/stobix/options","tip"}},
            {numberer,".*",{hg,"https://github.com/stobix/numberer","tip"}},
            {lager,".*",{git,"https://github.com/basho/lager.git","master"}},
            {vol_tools,".*",{hg,"github.com/stobixvolatile/vol_tools","tip"}},
            {erlando,".*",{hg,"https://volatile@bitbucket.org/volatile/erlando_sans_transforms","tip"}},
            {pid_numberer,".*",{hg,"https://volatile@bitbucket.org/volatile/pid_numberer","tip"}},
            {fuserl,".*",{git,"https://github.com/tonyrog/fuserl","master"}}
        ] }
]
end.
